const dataKeyboardEng = [
  [
    { letter: '1', class: 'key-button key-small', id: 49, code: 'Digit1' },
    { letter: '2', class: 'key-button key-small', id: 50, code: 'Digit2' },
    { letter: '3', class: 'key-button key-small', id: 51, code: 'Digit3' },
    { letter: '4', class: 'key-button key-small', id: 52, code: 'Digit4' },
    { letter: '5', class: 'key-button key-small', id: 53, code: 'Digit5' },
    { letter: '6', class: 'key-button key-small', id: 54, code: 'Digit6' },
    { letter: '7', class: 'key-button key-small', id: 55, code: 'Digit7' },
    { letter: '8', class: 'key-button key-small', id: 56, code: 'Digit8' },
    { letter: '9', class: 'key-button key-small', id: 57, code: 'Digit9' },
    { letter: '0', class: 'key-button key-small', id: 48, code: 'Digit0' },
    { letter: '-', class: 'key-button key-small', id: 189, code: 'Minus' },
    { letter: '=', class: 'key-button key-small', id: 187, code: 'Equal' },
    { letter: 'Backspace', class: 'key-button key-medium', code: 'Backspace' },
  ],
  [
    { letter: 'Tab', class: 'key-button key-medium', id: 9, code: 'Tab' },
    { letter: 'q', class: 'key-button key-small', id: 81, code: 'KeyQ' },
    { letter: 'w', class: 'key-button key-small', id: 87, code: 'KeyW' },
    { letter: 'e', class: 'key-button key-small', id: 69, code: 'KeyE' },
    { letter: 'r', class: 'key-button key-small', id: 82, code: 'KeyR' },
    { letter: 't', class: 'key-button key-small', id: 84, code: 'KeyT' },
    { letter: 'y', class: 'key-button key-small', id: 89, code: 'KeyY' },
    { letter: 'u', class: 'key-button key-small', id: 85, code: 'KeyU' },
    { letter: 'i', class: 'key-button key-small', id: 73, code: 'KeyI' },
    { letter: 'o', class: 'key-button key-small', id: 79, code: 'KeyO' },
    { letter: 'p', class: 'key-button key-small', id: 80, code: 'Key' },
    {
      letter: '{',
      class: 'key-button key-small',
      id: 219,
      code: 'BracketLeft',
    },
    {
      letter: '}',
      class: 'key-button key-small',
      id: 221,
      code: 'BracketRight',
    },
  ],
  [
    { letter: 'CapsLock', class: 'key-button key-medium', code: 'CapsLock' },
    { letter: 'a', class: 'key-button key-small', id: 65, code: 'KeyA' },
    { letter: 's', class: 'key-button key-small', id: 83, code: 'KeyS' },
    { letter: 'd', class: 'key-button key-small', id: 68, code: 'KeyD' },
    { letter: 'f', class: 'key-button key-small', id: 70, code: 'KeyF' },
    { letter: 'g', class: 'key-button key-small', id: 71, code: 'KeyG' },
    { letter: 'h', class: 'key-button key-small', id: 72, code: 'KeyH' },
    { letter: 'j', class: 'key-button key-small', id: 74, code: 'KeyJ' },
    { letter: 'k', class: 'key-button key-small', id: 75, code: 'KeyK' },
    { letter: 'l', class: 'key-button key-small', id: 76, code: 'KeyL' },
    { letter: ';', class: 'key-button key-small', id: 186, code: 'Semicolon' },
    { letter: 'Enter', class: 'key-button key-medium', code: 'Enter' },
  ],
  [
    {
      letter: 'Shift',
      class: 'key-button key-medium',
      id: 'ShiftLeft',
      code: 'ShiftLeft',
    },
    { letter: 'z', class: 'key-button key-small', id: 90, code: 'KeyZ' },
    { letter: 'x', class: 'key-button key-small', id: 88, code: 'KeyX' },
    { letter: 'c', class: 'key-button key-small', id: 67, code: 'KeyC' },
    { letter: 'v', class: 'key-button key-small', id: 86, code: 'KeyV' },
    { letter: 'b', class: 'key-button key-small', id: 66, code: 'KeyB' },
    { letter: 'n', class: 'key-button key-small', id: 78, code: 'KeyN' },
    { letter: 'm', class: 'key-button key-small', id: 77, code: 'KeyM' },
    { letter: ',', class: 'key-button key-small', id: 188, code: 'Comma' },
    { letter: '.', class: 'key-button key-small', id: 190, code: 'Period' },
    { letter: '/', class: 'key-button key-small', id: 191, code: 'Slash' },
    {
      letter: 'Shift',
      class: 'key-button key-medium',
      id: 'ShiftRight',
      code: 'ShiftRight',
    },
  ],
  [
    { letter: 'RU/EN', class: 'key-button key-languages' },
    {
      letter: 'Ctrl',
      class: 'key-button key-medium',
      id: 'ControlLeft',
      code: 'ControlLeft',
    },
    {
      letter: 'Alt',
      class: 'key-button key-medium',
      id: 'AltLeft',
      code: 'AltLeft',
    },
    { letter: 'Space', class: 'key-button key-big', code: 'Space' },
    {
      letter: 'Alt',
      class: 'key-button key-medium',
      id: 'AltRight',
      code: 'AltRight',
    },
    {
      letter: 'Ctrl',
      class: 'key-button key-medium',
      id: 'ControlRight',
      code: 'ControlRight',
    },
  ],
];

const dataKeyboardRu = [
  [
    { letter: '!', class: 'key-button key-small', id: 49, code: 'Digit1' },
    { letter: '@', class: 'key-button key-small', id: 50, code: 'Digit2' },
    { letter: '#', class: 'key-button key-small', id: 51, code: 'Digit3' },
    { letter: '$', class: 'key-button key-small', id: 52, code: 'Digit4' },
    { letter: '%', class: 'key-button key-small', id: 53, code: 'Digit5' },
    { letter: '^', class: 'key-button key-small', id: 54, code: 'Digit6' },
    { letter: '&', class: 'key-button key-small', id: 55, code: 'Digit7' },
    { letter: '*', class: 'key-button key-small', id: 56, code: 'Digit8' },
    { letter: '(', class: 'key-button key-small', id: 57, code: 'Digit9' },
    { letter: ')', class: 'key-button key-small', id: 48, code: 'Digit0' },
    { letter: '_', class: 'key-button key-small', id: 189, code: 'Minus' },
    { letter: '+', class: 'key-button key-small', id: 187, code: 'Equal' },
    { letter: 'Backspace', class: 'key-button key-medium', code: 'Backspace' },
  ],
  [
    { letter: 'Tab', class: 'key-button key-medium', id: 9, code: 'Tab' },
    { letter: 'й', class: 'key-button key-small', id: 81, code: 'KeyQ' },
    { letter: 'ц', class: 'key-button key-small', id: 87, code: 'KeyW' },
    { letter: 'у', class: 'key-button key-small', id: 69, code: 'KeyE' },
    { letter: 'к', class: 'key-button key-small', id: 82, code: 'KeyR' },
    { letter: 'е', class: 'key-button key-small', id: 84, code: 'KeyT' },
    { letter: 'н', class: 'key-button key-small', id: 89, code: 'KeyY' },
    { letter: 'г', class: 'key-button key-small', id: 85, code: 'KeyU' },
    { letter: 'ш', class: 'key-button key-small', id: 73, code: 'KeyI' },
    { letter: 'щ', class: 'key-button key-small', id: 79, code: 'KeyO' },
    { letter: 'з', class: 'key-button key-small', id: 80, code: 'KeyP' },
    {
      letter: '[',
      class: 'key-button key-small',
      id: 219,
      code: 'BracketLeft',
    },
    {
      letter: ']',
      class: 'key-button key-small',
      id: 221,
      code: 'BracketRight',
    },
  ],
  [
    { letter: 'CapsLock', class: 'key-button key-medium', code: 'CapsLock' },
    { letter: 'ф', class: 'key-button key-small', id: 65, code: 'KeyA' },
    { letter: 'ы', class: 'key-button key-small', id: 83, code: 'KeyS' },
    { letter: 'в', class: 'key-button key-small', id: 68, code: 'KeyD' },
    { letter: 'а', class: 'key-button key-small', id: 70, code: 'KeyF' },
    { letter: 'п', class: 'key-button key-small', id: 71, code: 'KeyG' },
    { letter: 'р', class: 'key-button key-small', id: 72, code: 'KeyH' },
    { letter: 'о', class: 'key-button key-small', id: 74, code: 'KeyJ' },
    { letter: 'л', class: 'key-button key-small', id: 75, code: 'KeyK' },
    { letter: 'д', class: 'key-button key-small', id: 76, code: 'KeyL' },
    { letter: 'ж', class: 'key-button key-small', id: 186, code: 'Semicolon' },
    { letter: 'Enter', class: 'key-button key-medium', code: 'Enter' },
  ],
  [
    { letter: 'Shift', class: 'key-button key-medium', id: 'ShiftLeft' },
    { letter: 'я', class: 'key-button key-small', id: 90, code: 'KeyZ' },
    { letter: 'ч', class: 'key-button key-small', id: 88, code: 'KeyX' },
    { letter: 'с', class: 'key-button key-small', id: 67, code: 'KeyC' },
    { letter: 'м', class: 'key-button key-small', id: 86, code: 'KeyV' },
    { letter: 'и', class: 'key-button key-small', id: 66, code: 'KeyB' },
    { letter: 'т', class: 'key-button key-small', id: 78, code: 'KeyN' },
    { letter: 'ь', class: 'key-button key-small', id: 77, code: 'KeyM' },
    { letter: 'б', class: 'key-button key-small', id: 188, code: 'Comma' },
    { letter: 'ю', class: 'key-button key-small', id: 190, code: 'Period' },
    { letter: '?', class: 'key-button key-small', id: 191, code: 'Slash' },
    {
      letter: 'Shift',
      class: 'key-button key-medium',
      id: 'ShiftRight',
      code: 'ShiftRight',
    },
  ],
  [
    { letter: 'RU/EN', class: 'key-button key-languages' },
    {
      letter: 'Ctrl',
      class: 'key-button key-medium',
      id: 'ControlLeft',
      code: 'ControlLeft',
    },
    {
      letter: 'Alt',
      class: 'key-button key-medium',
      id: 'AltLeft',
      code: 'AltLeft',
    },
    { letter: 'Space', class: 'key-button key-big', code: 'Space' },
    {
      letter: 'Alt',
      class: 'key-button key-medium',
      id: 'AltRight',
      code: 'AltRight',
    },
    {
      letter: 'Ctrl',
      class: 'key-button key-medium',
      id: 'ControlRight',
      code: 'ControlRight',
    },
  ],
];

const dataKeyboard = {
  en: dataKeyboardEng,
  ru: dataKeyboardRu,
};

export default dataKeyboard;
