export const valueButtons = {
  englishLang: 'en',
  russianLang: 'ru',
  shiftButton: 'Shift',
  ctrlButton: 'Ctrl',
  altButton: 'Alt',
  langButton: 'RU/EN',
  capsLockButton: 'CapsLock',
  enterButton: 'Enter',
  spaceButton: 'Space',
  ampersand: '&',
  ampersandSymbol: '&amp;',
  tabButton: 'Tab',
  backspaceButton: 'Backspace',
  controlLeftButton: 'ControlLeft',
  controlRight: 'ControlRight',
  altLeftButton: 'AltLeft',
  altRightButton: 'AltRight',
  shiftLeftButton: 'ShiftLeft',
  shiftRightButton: 'ShiftRight',
  metaButton: 'Meta',
  tabSymbol: '\t',
  enterSymbol: '\n',
  emptyString: ' ',
};
